// <auto-generated />
namespace proje_obs.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class test_test1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(test_test1));
        
        string IMigrationMetadata.Id
        {
            get { return "201612201020271_test_test1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
